### PR TITLE
Prevent basename from being replaced in the middle of the route

### LINKED ISSUE #229: Route gets basename strip out and breaks matching
So I'm using basename `/app` and I have a route which is something like: `/loans/:loanId/apply/start` and redux-little-router will match as `/loans/:loanId"ly"/start` because `/apply` contains `/app`.

It's very easy to reproduce. Just have a basename which is not only `/` and use that anywhere in your router definition.

I'm using version `14.2.0`

### PR DESCRIPTION
**Pull request by GuilhermeMedeiros**
Fixes #229

### CODE REVIEW

**Comment by ZwaarContrast** [comment]
Please implement this, running into this issue as well.

File: src/environment/browser-router.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default (
   } = history.location;
 
   // Strip the basename from the initial pathname
-  const pathname = basename ? fullPathname.replace(basename, '') : fullPathname;
+  const pathname = basename ? fullPathname.replace(new RegExp(`^${basename}`), '') : fullPathname
```
Comment (aweary) [inline src/environment/browser-router.js]: I think we can simplify this to avoid dynamically allocating a `RegExp` instance by doing a substring match + replace instead.

```js
const pathname = basename && fullPathname.indexOf(basename) === 0
  ? fullPathname.slice(basename.length)
  : fullPathname;

Comment (GuilhermeMedeiros) [reply src/environment/browser-router.js]: Smart! I've pushed the changes you requested.

**Comment by tptee** [comment]
@aweary we can ignore codacy and bithound for now until we update deps
